M48
; DRILL file KiCad 10.0.6 date 2026-09-26T13:18:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T13:18:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X120.5Y-88.95
X120.5Y-95.95
X135.0Y-88.95
X135.0Y-95.95
T2
X103.5Y-73.5
X103.5Y-96.5
X161.5Y-73.5
X161.5Y-96.5
M30
