M48
; DRILL file {KiCad 8.0.5} date 2024-10-03T09:55:34+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-03T09:55:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X5.1063Y-3.4016
X5.1063Y-3.6772
T2
X4.0748Y-2.8937
X4.0748Y-3.7992
X6.3583Y-2.8937
X6.3583Y-3.7992
M30
